### ISSUE TITLE
 PDU/Network error: EOF on receive ESME_RTHROTTLED in submit sm resp

### ISSUE THREAD

**Issue by parsibox** [linxGnu/gosmpp#118] opened 2023-11-07 17:07 UTC
hi
when i send an sms and receive error like ESME_RTHROTTLED client disconnect and say  PDU/Network error: EOF
 
![image](https://github.com/linxGnu/gosmpp/assets/12513476/26f1a9e3-3035-45ff-9787-cc2112323843)

![image](https://github.com/linxGnu/gosmpp/assets/12513476/774a9011-1353-46de-94b1-142720695a30)

**Comment by laduchesneau** [comment] 2023-11-07 22:58
When the libraries decodes the PDU, the submit_sm_resp, the [Parse](https://github.com/linxGnu/gosmpp/blob/master/pdu/PDU.go#L158) func generate the EOF error and is caught by the [check](https://github.com/linxGnu/gosmpp/blob/master/receivable.go#L70) in receivables.go. This will restart the bind.

Looking at your pcap, why is the sequence set to 0 ? Shouldnt your SMSC retrun the sequence # from the submit_sm pdu ? 

That said, this is the cause EOF the issue. Its a bug with the parser when sequence is set to 0, its returning a EOF when sequence is set to 0. I am able to reproduce with a test.

**Comment by laduchesneau** [comment] 2023-11-07 23:06
Ive copied you submit_sm_resp into PDU_test.go and it fails. I initially thought it was the sequence number being 0, but it looks like its more to do with the command_status.

**Comment by parsibox** [comment] 2023-11-08 08:56
i manually set  sequence to 0 on submit sm
but why pdu test failed?

**Comment by linxGnu** [comment] 2023-11-08 09:18
@parsibox It looks to me that above error is throttling from SMSC.

- How many messages are you trying to send to SMSC within 1 minute / 1 second?
- How does your SMSC's rate limit look like?

**Comment by parsibox** [comment] 2023-11-08 09:21
> @parsibox It looks to me that above error is throttling from SMSC.
> 
> * How many messages are you trying to send to SMSC within 1 minute / 1 second?
> * How does your SMSC's rate limit look like?

yes i know it is throttling  error 
but my question is why this lib can not pars it?
it goes unbind and and reconnect when this pdu receive
this is a standard pdu for rate limit on submit sm
we should get this error and like this error code on submit sm resp without undind and we want to get that error code

**Comment by laduchesneau** [comment] 2023-11-10 13:38
Your issue with the bind closing after receiving a response to a failed submit_sm, should be resolved in #119. The PR was included in the latest release, v0.1.9.

**Closed** 2023-11-18 15:09 UTC
